#pragma once

#include <string>
#include <array>
#include <json.hpp>

//Guid contains 32 randomly generated bytes,
//Meaning each one generated is extremely unlikely to be the same
//This is similar to the stardard way of generating them
//BUT!!!!
//This method doesn't use any bits to indicate version or anything, since we're only using them within the program

class Guid
{
private:
	std::array<unsigned char, 32> m_guid;

public:
	Guid();
	Guid(const std::string& str);

	std::string ToString() const;

	Guid& operator=(const Guid& other);

	bool operator==(const Guid& other) const;

	static Guid GetZeroGuid();
};

void to_json(nlohmann::json& json, const Guid& guid);
void from_json(const nlohmann::json& json, Guid& guid);

